version: '3'

services: 

    db:
        image: postgres
        restart: always
        env_file: database.conf
        volumes:    
            - ./postgres-data/postgres:/var/lib/postgresql

        ports:
            - 5432:5432

    app:
        build: .
        ports: 
            - 8000:8000
        depends_on: 
            - db